AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  Exclude:
    - 'temp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
