name: Tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.2'
          - '3.2.2'
          - '2.7.8'
          - '2.3.8'

    steps:
    - name: Dependencies
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: libyajl2 libyajl-dev valgrind
    - uses: actions/checkout@v4
    - name: Use proper Gemfile.lock
      if: ${{ matrix.ruby == '2.3.8' }}
      run: mv Gemfile_old_ruby.lock Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Run valgrind
      if: ${{ matrix.ruby != '2.3.8' }}
      run: bundle exec rake spec:valgrind
