name: Tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.2'
          - '3.2.2'
          - '2.7.8'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install libraries
      run: sudo apt install -y libyajl2 libyajl-dev
    - name: Run the default task
      run: bundle exec rake
    # TODO: all valgrind run, at least for tags
